[package]
authors = ["Dingping Zhang <DingpingZhang@outlook.com>"]
edition = "2018"
name = "game_2048_rust"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
rand = "0.8.0"
